---
kube_version: 1.36.2
container_manager: containerd
kube_network_plugin: flannel

kube_service_addresses: 10.96.0.0/12
kube_pods_subnet: 10.244.0.0/16
kube_network_node_prefix: 24

kube_proxy_mode: iptables
kube_proxy_strict_arp: true
dns_mode: coredns
enable_nodelocaldns: true

kubeconfig_localhost: true
kubectl_localhost: true
helm_enabled: true
