all:
  vars:
    ansible_user: deploy
    ansible_become: true
    kube_version: v1.34.3
    pod_subnet: 10.244.0.0/16
    service_subnet: 10.96.0.0/12
    control_plane_endpoint: k8s-api.internal:6443
    harbor_registry: harbor.internal
    harbor_project: k8s
    local_path: /var/local-path-provisioner
  children:
    control_plane:
      hosts:
        cp-01:
          ansible_host: 10.10.0.11
    workers:
      hosts:
        worker-01:
          ansible_host: 10.10.0.21
