user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 256;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;
    sendfile on;

    server {
        listen 80 default_server;
        server_name _;
        root /usr/share/nginx/html;

        location = /healthz {
            access_log off;
            default_type text/plain;
            return 200 "ok\n";
        }

        location /debian/ {
            autoindex on;
        }
    }
}
